interface BarangaysOfCitiesData {
  id: number;
  city: string;
  barangays: string[];
}

export const BarangaysOfCities: BarangaysOfCitiesData[] = [
  {
    id: 1,
    city: "Calamba",
    barangays: [
      "Bagong Kalsada",
      "Banlic",
      "Barandal",
      "Barrio Siete",
      "Batino",
      "Bucal",
      "Bunggo",
      "Burol",
      "Canlubang",
      "Hornalan",
      "Kay-Anlog",
      "La Mesa",
      "Lecheria",
      "Looc",
      "Mabato",
      "Majada Out",
      "Majada In",
      "Makiling",
      "Mapagong",
      "Masili",
      "Maunong",
      "Mayapa",
      "Milagrosa",
      "Paciano Rizal",
      "Palingon",
      "Palo-Alto",
      "Pansol",
      "Prinza",
      "Punta",
      "Saimsim",
      "Sampiruhan",
      "San Cristobal",
      "San Isidro",
      "San Jose",
      "San Juan",
      "San Pedro",
      "San Roque",
      "Silangan",
      "Sirang Lupa",
      "Sucol",
      "Sungay",
      "Turbina",
      "Ulango",
      "Unang Sigaw",
      "Uno",
    ],
  },
  {
    id: 2,
    city: "Cabuyao",
    barangays: [
      "Baclaran",
      "Banaybanay",
      "Banlic",
      "Bigaa",
      "Butong",
      "Casile",
      "Diezmo",
      "Gulod",
      "Mamatid",
      "Marinig",
      "Niugan",
      "Pittland",
      "Poblacion Uno",
      "Poblacion Dos",
      "Poblacion Tres",
      "Pulo",
      "Sala",
      "San Isidro",
    ],
  },
  {
    id: 3,
    city: "Santa Rosa",
    barangays: [
      "Aplaya",
      "Balibago",
      "Caingin",
      "Dila",
      "Dita",
      "Don Jose",
      "Ibaba",
      "Kanluran (Poblacion Uno)",
      "Labas",
      "Macabling",
      "Malitlit",
      "Malusak (Poblacion Dos)",
      "Market Area (Poblacion Tres)",
      "Pooc (Pook)",
      "Pulong Santa Cruz",
      "Santo Domingo",
      "Sinalhan",
      "Tagapo",
    ],
  },
];
