export const SantaRosa = [
  "Aplaya",
  "Balibago",
  "Caingin",
  "Dila",
  "Dita",
  "Don Jose",
  "Ibaba",
  "Kanluran (Poblacion Uno)",
  "Labas",
  "Macabling",
  "Malitlit",
  "Malusak (Poblacion Dos)",
  "Market Area (Poblacion Tres)",
  "Pooc (Pook)",
  "Pulong Santa Cruz",
  "Santo Domingo",
  "Sinalhan",
  "Tagapo",
];
